"""Constants for the RackLink integration."""
from __future__ import annotations

DOMAIN = "racklink"
MANUFACTURER = "Middle Atlantic"

# Protocol constants
PROTOCOL_HEADER = 0xFE
PROTOCOL_TAIL = 0xFF
PROTOCOL_ESCAPE = 0xFD
PROTOCOL_PORT = 60000

# Command codes
CMD_PING = 0x01
CMD_LOGIN = 0x02
CMD_NACK = 0x10
CMD_POWER_OUTLETS = 0x20
CMD_OUTLET_NAME = 0x21
CMD_OUTLET_COUNT = 0x22
CMD_ENERGY_MGMT = 0x23
CMD_DRY_CONTACTS = 0x30
CMD_CONTACT_NAME = 0x31
CMD_CONTACT_COUNT = 0x32
CMD_SEQUENCE = 0x36
CMD_EPO = 0x37
CMD_LOG_ALERTS = 0x40
CMD_STATUS_CHANGE = 0x41
CMD_SENSORS_START = 0x50
CMD_SENSORS_END = 0x61
CMD_THRESHOLDS_START = 0x70
CMD_THRESHOLDS_END = 0x77
CMD_READ_LOG = 0x80
CMD_LOG_COUNT = 0x81
CMD_CLEAR_LOG = 0x82
CMD_PRODUCT_PART = 0x90
CMD_PRODUCT_RATING = 0x91
CMD_PRODUCT_SURGE = 0x93
CMD_PRODUCT_IP = 0x94
CMD_PRODUCT_MAC = 0x95

# Subcommands
SUB_SET = 0x01
SUB_GET = 0x02
SUB_RESPONSE = 0x10
SUB_STATUS_UPDATE = 0x12
SUB_LOG_UPDATE = 0x30

# Configuration keys
CONF_HOST = "host"
CONF_PORT = "port"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"

# Defaults
DEFAULT_PORT = 60000
DEFAULT_USERNAME = "user"
